### ISSUE TITLE
No support for Linux

### ISSUE THREAD

**Issue by justinhj** [justinhj/battery.nvim#1]
Currently only Windows (via Powershell) and macOS (via pmset) are supported. Add support for Linux.

Acceptance Criteria

Should be as portable as possible. Should work without installing software IF possible.

For guidance start with the files powershell.lua and pmset.lua and modify for the Linux tool that works best.

**Comment by justinhj** [comment]
Some notes:

"WSL's kernel doesn't expose ACPI information"
https://askubuntu.com/questions/1043068/how-to-i-check-the-battery-level-on-a-microsoft-surface-from-a-wsl-ubuntu-shell

Seems you can get it from the file system (if no battery though it will show file not found)
```
/sys/class/power_supply/BAT1/capacity
/sys/class/power_supply/BAT0/capacity
/sys/class/power_supply/battery/capacity
```

**Comment by justinhj** [comment]
Arch linux
https://wiki.archlinux.org/title/laptop#ACPI

**Comment by tomhampshire** [comment]
The Linux kernel exposes a read-only "file" at `/sys/class/power_supply/BAT0/capacity` which will display values from `0` to `100` which correspond with the battery level.
This is at the kernel level, so should work for all distributions.
