### ISSUE TITLE
ACPI shows average battery power when mouse with battery added

### ISSUE THREAD

**Issue by FMMazur** [justinhj/battery.nvim#12]
I think it's very necessary, as I have several devices that shows in `acpi` and, in the current situation, ends up breaking the percentage.
![](https://i.imgur.com/E3aaR8W.png)

as the image shows, it should be 56%, but shows 28%.

In this case, the first one is my notebook battery, and the last one is my mouse.
![battery info](https://i.imgur.com/cDcaIje.png)

The solution I found is quite simple, but I can't possible say it solves all cases.

**Comment by justinhj** [comment]
@FMMazur thank you for submitting this issue.
This relates to #7 
This is interesting; I assumed that if a user had multiple batteries it would be okay to show the average, assuming they are all laptop power. But I see that other batteries show up and it makes no sense. I will make an update soon to show only the first battery power.

**Comment by netfri25** [comment]
Is there an update on this issue? I have the exact same problem

**Comment by justinhj** [comment]
Yes just updated it this morning. Please grab the latest or set the tag to v.0.5.0 and let me know if it is fixed. The new behaviour takes the first battery found.

**Comment by FMMazur** [comment]
I believe that the way it is implemented in the commit may not always works, I will check it later.

**Comment by justinhj** [comment]
I may have to make it either display multiple batteries or pick one based on some criteria. Let me know if you see any documentation on how acpi reports.

**Comment by netfri25** [comment]
It still has some issues.
The order of the batteries is not always the same, which makes it sometimes show 0%

![Screenshot from 2022-11-19 10-04-41](https://user-images.githubusercontent.com/40868480/202841406-5628443a-5515-458f-8367-809eed1c769d.png)
![Screenshot from 2022-11-19 10-04-54](https://user-images.githubusercontent.com/40868480/202841421-5c73f013-5fec-4105-baf2-1ff774b8d9e8.png)

**Comment by netfri25** [comment]
I don't really know how to program in Lua so I have no idea how to implement this, but in `/sys/class/power_supply/BAT0/` there is a file called `capacity` which stores the battery percentage

**Comment by justinhj** [comment]
@netfri25 thanks for the info. I think the problem with using the file system is that it varies across different linux distributions, whereas the if I require the user to install acpi that levels the playing field. Unfortunately I don't have any idea how acpi orders the batteries so not sure how to pick one.

**Comment by justinhj** [comment]
I'm going to add a new configuration variable 'multiple_battery_selection'
1. "max" will choose the battery with the highest percentage power
2. "avg" will average the battery percentages
3. 1,2,3... will choose the first, second, third battery reported
It will default to 1 so the existing behaviour will be unchanged.
This will initially only be implemented for linux/acpi.

**Comment by FMMazur** [comment]
I found something in [MSDN](https://learn.microsoft.com/en-us/windows-hardware/design/component-guidelines/acpi-battery-and-power-subsystem-firmware-implementation), it says, the device can send the _SUN method as specified on [ACPI Reference](https://uefi.org/sites/default/files/resources/ACPI_6_3_May16.pdf#page410). So it can be a firmware that don't send that optional method or it could be some driver problem as related at [this](https://www.reddit.com/r/archlinux/comments/wwcpeu/laptop_acpi_battery_status_not_working/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) reddit post.

**Comment by justinhj** [comment]
I've implemented the multiple_battery_selection option in the branch `battery-chooser`.

```
battery.setup({
	update_rate_seconds = 30,           -- Number of seconds between checking battery status
	show_status_when_no_battery = true, -- Don't show any icon or text when no battery found (desktop for example)
	show_plugged_icon = true,           -- If true show a cable icon alongside the battery icon when plugged in
	show_unplugged_icon = true,         -- When true show a diconnected cable icon when not plugged in
	show_percent = true,                -- Whether or not to show the percent charge remaining in digits
    vertical_icons = true,              -- When true icons are vertical, otherwise shows horizontal battery icon
    multiple_battery_selection = 1,     -- Which battery to choose when multiple found. "max" or "maximum", "min" or "minimum" or a number to pick the nth battery found (currently linux acpi only)
})
```
I don't have a linux machine handy to test this on so I'm not ready to push to main, but if anyone can verify that it works and helps with this issue I will do so.

**Comment by justinhj** [comment]
@netfri25 in your case I would set `multiple_battery_selection = max,` so that you always get the battery that is charged not the 0%.

**Comment by netfri25** [comment]
Now it works perfectly!! Thanks a lot, I truly appreciate the effort!
