### ISSUE TITLE
Weird error in Linux.

### ISSUE THREAD

**Issue by Norok-The-Diablo** [justinhj/battery.nvim#18]
My config is:
`
lua << EOF
local nvimbattery = {
  function()
    return require("battery").get_status_line()
  end
}
EOF
lua << EOF
require('lualine').setup {
    options = {
        theme = "catppuccin",
        icons_enabled = true
    },
    sections = {
        lualine_a = {'mode'},
        lualine_b = {'branch', 'diff', 'diagnostics'},
        lualine_c = {'filename'},
        lualine_x = {'encoding', 'fileformat', 'filetype'},
        lualine_y = {'location'},
        lualine_z = {nvimbattery, 'ctime'}
  }
}
EOF
`
And I have acpi installed in Linux, but I get this weird error everytime:
`
Error executing vim.schedule lua callback: ...k/.local/share/nvim/plugged/lualine.

nvim/lua/lualine.lua:432: Error executing lua: .../nvim/plugged/lualine.nvim/lua/l

ualine/utils/section.lua:38: attempt to get length of a nil value

stack traceback:

.../nvim/plugged/lualine.nvim/lua/lualine/utils/section.lua:38: in functio

n 'draw_section'

...k/.local/share/nvim/plugged/lualine.nvim/lua/lualine.lua:173: in functi

on 'statusline'

...k/.local/share/nvim/plugged/lualine.nvim/lua/lualine.lua:301: in functi

on <...k/.local/share/nvim/plugged/lualine.nvim/lua/lualine.lua:282>

[C]: in function 'nvim_win_call'

...k/.local/share/nvim/plugged/lualine.nvim/lua/lualine.lua:432: in functi

on 'refresh'

...k/.local/share/nvim/plugged/lualine.nvim/lua/lualine.lua:356: in functi

on <...k/.local/share/nvim/plugged/lualine.nvim/lua/lualine.lua:355>

stack traceback:

[C]: in function 'nvim_win_call'

...k/.local/share/nvim/plugged/lualine.nvim/lua/lualine.lua:432: in functi

on 'refresh'
`
Any ideas about what's happening?

**Comment by justinhj** [comment]
Could you check it if it's a problem with your lua line config or the plugin, by running this command:
`:lua vim.print(require("battery").get_status_line())`
If all is well you should see the battery status.

**Comment by justinhj** [comment]
Closing as it has been open for 6 months and no further information was provided.
