### ISSUE TITLE
bug: `util.file.is_readable_directory()` does not work on Termux

### ISSUE THREAD

**Issue by Agent-E11** [justinhj/battery.nvim#41]
On Termux, the `/sys/class/power_supply` exists and "is readable", except it, well, isn't.

```sh
$ stat --format='%A' /sys/class/power_supply
drwxr-xr-x
#      ^ Everyone can read it
```
```sh
$ ls /sys/class/power_supply
ls: cannot open directory '/sys/class/power_supply': Permission denied
#                                                    ^^^^^^^^^^^^^^^^^ I can't read it?
```

I have found a method that I think works on both regular Linux and Termux (not Windows though):

```sh
$ test -d /sys/class/power_supply && test -r /sys/class/power_supply
#      ^^ Is directory                    ^^ Is readable
```

This is communicated through the exit code, which is returned by the [`os.execute`](https://www.lua.org/manual/5.1/manual.html#pdf-os.execute) function (I think Neovim uses Lua 5.1, so this version of `os.execute` only returns the exit code)

```lua
function is_readable_directory(file)
  return os.execute('test -d '..file..' && test -r '..file) == 0
end
```

The problem with this is that the input must be trustworthy, because the `file` could be something like `/some/file; rm -rf /`

**Comment by Agent-E11** [comment]
I have created a draft pull request with some proposed changes

**Comment by justinhj** [comment]
Interesting. Since termux is a special case, is there an environment flag we can use to detect Termux and then use a different code path for that?

**Comment by Agent-E11** [comment]
There is a `$TERMUX_VERSION` environment variable, and I am looking into whether that is a reliable way of detecting if it is running in Termux

**Comment by Agent-E11** [comment]
I have made it so that it checks whether it is in Termux, and will use the "old" or "new" version of the function based on that
