### ISSUE TITLE
Error on my Windows device with no battery

### ISSUE THREAD

**Issue by Norok-The-Diablo** [justinhj/battery.nvim#50]
I work on a laptop and a desktop, and I liked this plugin because it could make my config go in between the two with an extra QOL feature on my laptop. It works fine on my laptop, but on my desktop with no battery every time the plugin checks if I have a battery it gives this error:

Error executing luv callback:
.../plugged/battery.nvim/lua/battery/parsers/powershell.lua:57: attempt to index a nil value
stack traceback:
        .../plugged/battery.nvim/lua/battery/parsers/powershell.lua:57: in function 'parse_powershell_battery_info'
        .../plugged/battery.nvim/lua/battery/parsers/powershell.lua:79: in function '_user_on_exit'
        ...Local/nvim-data/plugged/plenary.nvim/lua/plenary/job.lua:241: in function '_shutdown'                                ...Local/nvim-data/plugged/plenary.nvim/lua/plenary/job.lua:48: in function <...Local/nvim-data/plugged/plenary.nvim/lua/plenary/job.lua:39>  

which makes sense because there's no battery, but I read on the ReadMe that it can detect if there isn't a battery and not cause harm. If that's only a feature in Linux, then I guess this is an enhancement issue.

**Comment by Norok-The-Diablo** [comment]
Im loading battery.nvim in lualine like this:

lua << EOF
local batterycolor = "#ec9ca4"
local battery = require("battery")
battery.setup({
	update_rate_seconds = 30,           -- Number of seconds between checking battery status
	show_status_when_no_battery = true, -- Don't show any icon or text when no battery found (desktop for example)
	show_plugged_icon = true,           -- If true show a cable icon alongside the battery icon when plugged in
	show_unplugged_icon = true,         -- When true show a diconnected cable icon when not plugged in
	show_percent = true,                -- Whether or not to show the percent charge remaining in digits
    vertical_icons = true,              -- When true icons are vertical, otherwise shows horizontal battery icon
    multiple_battery_selection = 1,     -- Which battery to choose when multiple found. "max" or "maximum", "min" or "minimum" or a number to pick the nth battery found (currently linux acpi only)
})
EOF
lua << EOF
require('lualine').setup {
    options = {
        theme = 'catppuccin',
        icons_enabled = true
    },
    nvimbattery = {
        function()
            return require("battery").get_status_line()
        end,
        color = { fg = batterycolor, bg = bg },
    },
    extensions = {
	'nerdtree'
    },
    sections = {
        lualine_a = {'mode'},
        lualine_b = {'branch', 'diff', 'diagnostics'},
        lualine_c = {'filename'},
        lualine_w = {'encoding', 'fileformat', 'filetype'},
        lualine_x = {'location'},
        lualine_y = {'ctime'},
        lualine_z = {'nvimbattery'}
  },
}
EOF

**Comment by Norok-The-Diablo** [comment]
I also tried running ```:lua vim.print(require("battery").get_status_line())``` manually and the output was a battery with a question mark

**Comment by Norok-The-Diablo** [comment]
I just cleaned my syntax, but same issue

```
lua << EOF
local batterycolor = '#ec9ca4'
local battery = require('battery')
battery.setup({
	update_rate_seconds = 30,
	show_status_when_no_battery = true,
	show_plugged_icon = true,
	show_unplugged_icon = true,
	show_percent = true,
    vertical_icons = true,
    multiple_battery_selection = 1
})
EOF
lua << EOF
local nvimbattery = {
        function()
            return require('battery').get_status_line()
        end,
        color = { fg = batterycolor, bg = bg }
}
EOF
lua << EOF
require('lualine').setup {
    options = {
        theme = 'catppuccin',
        icons_enabled = true
    },
    extensions = {
	'nerdtree'
    },
    sections = {
        lualine_a = {'mode'},
        lualine_b = {'branch', 'diff', 'diagnostics'},
        lualine_c = {'filename'},
        lualine_w = {'encoding', 'fileformat', 'filetype'},
        lualine_x = {'location'},
        lualine_y = {'ctime'},
        lualine_z = {'nvimbattery'}
  },
}
EOF
```

**Comment by Norok-The-Diablo** [comment]
I updated to the latest version on my laptop and nothing is showing, no errors, but no battery

**Comment by justinhj** [comment]
Thank you for the report Norok I will investigate when I get time 👍🏽

**Comment by Norok-The-Diablo** [comment]
Sounds good

**Comment by Agent-E11** [comment]
@Norok-The-Diablo I think I found the issue. I have a fork with the branch `50-fix-error-on-windows-no-battery` with the fix

**Comment by Agent-E11** [comment]
You can see the diff here https://github.com/justinhj/battery.nvim/pull/51

**Comment by Agent-E11** [comment]
I am not sure how you manage your packages, but I will assume vim-plug since it looks like you are using `.vimrc`:
```vim
Plug 'agent-e11/battery.nvim', { 'branch': '50-fix-error-on-windows-no-battery' }
```

**Comment by Norok-The-Diablo** [comment]
Thanks so much!

**Comment by Agent-E11** [comment]
@Norok-The-Diablo Did it fix it?

**Comment by Norok-The-Diablo** [comment]
Just got home, I will test right now

**Comment by Norok-The-Diablo** [comment]
No more error, it just shows nothing on desktop

**Comment by Norok-The-Diablo** [comment]
I will try this version on my laptop too

**Comment by Agent-E11** [comment]
@Norok-The-Diablo Oh, I forgot to mention. I think the reason that it shows nothing is because in your config you wrote:
```lua
lualine_z = { 'nvimbattery' }
```
instead of
```lua
lualine_z = { nvimbattery }
```

**Comment by Norok-The-Diablo** [comment]
on my init I have it without quotes so that's not it

**Comment by Norok-The-Diablo** [comment]
I realized I did it wrong later

**Comment by Agent-E11** [comment]
What is the output of `require("battery").get_battery_status()`?

**Comment by Norok-The-Diablo** [comment]
nothing

**Comment by Agent-E11** [comment]
"Nothing" meaning:
```lua
{}
```
or
```
```
?

**Comment by Norok-The-Diablo** [comment]
nothing nothing

**Comment by Norok-The-Diablo** [comment]
nothing on my laptop either

**Comment by Norok-The-Diablo** [comment]
just tried it

**Comment by Norok-The-Diablo** [comment]
It's loaded like this:

```
lua << EOF
local batterycolor = '#ec9ca4'
local battery = require('battery')
battery.setup({
	update_rate_seconds = 30,
	show_status_when_no_battery = true,
	show_plugged_icon = true,
	show_unplugged_icon = true,
	show_percent = true,
    vertical_icons = true,
    multiple_battery_selection = 1
})
EOF
lua << EOF
local nvimbattery = {
        function()
            return require('battery').get_status_line()
        end,
        color = { fg = batterycolor, bg = bg }
}
EOF
lua << EOF
require('lualine').setup {
    options = {
        theme = 'catppuccin',
        icons_enabled = true
    },
    extensions = {
	'nerdtree'
    },
    sections = {
        lualine_a = {'mode'},
        lualine_b = {'branch', 'diff', 'diagnostics'},
        lualine_c = {'filename'},
        lualine_w = {'encoding', 'fileformat', 'filetype'},
        lualine_x = {'location'},
        lualine_y = {'ctime'},
        lualine_z = {nvimbattery}
  },
}
EOF
```

**Comment by Agent-E11** [comment]
can you verify that you have the proper branch checked out?

Go to the directory the plugin is installed to and run:
```sh
git remote --verbose
git branch
```

**Comment by Norok-The-Diablo** [comment]
yeah everything's right

**Comment by Agent-E11** [comment]
Ok, run this directly:
```
:lua =require"battery".get_battery_status()
```

**Comment by Norok-The-Diablo** [comment]
```
{
  ac_power = true,                                                                                                        battery_count = 0,                                                                                                      method = "powershell",                                                                                                  percent_charge_remaining = 100                                                                                        }                 
```

**Comment by Norok-The-Diablo** [comment]
thats the output

**Comment by Agent-E11** [comment]
Yeah, that is what it's supposed to be. 🤔

Try this:
```
:lua =require"battery".get_status_line()
```

**Comment by Norok-The-Diablo** [comment]
there's a desktop icon

**Comment by Norok-The-Diablo** [comment]
so weird

**Comment by Agent-E11** [comment]
Now, replace this:
```lua
lualine_z = {nvimbattery}
```
with this:
```lua
lualine_z = { { require("battery").get_status_line } }
```

**Comment by Norok-The-Diablo** [comment]
It works now

**Comment by Norok-The-Diablo** [comment]
What the heck

**Comment by Norok-The-Diablo** [comment]
so how I'm loading nvimbattery in the function must be wrong

**Comment by Agent-E11** [comment]
maybe just replace this:
```lua
local nvimbattery = {
        function()
            return require('battery').get_status_line()
        end,
        color = { fg = batterycolor, bg = bg }
}
```
with this:
```lua
local nvimbattery = {
        require("battery").get_status_line,
        color = { fg = batterycolor, bg = bg }
}
```

**Comment by Norok-The-Diablo** [comment]
If I remove the color variable it doesn't work either

**Comment by Norok-The-Diablo** [comment]
Does it have to be nested in the lualine setup?

**Comment by Agent-E11** [comment]
That is really strange

**Comment by Agent-E11** [comment]
Actually, remove the
```vim
EOF
lua<<EOF
```
between the declaration of `nvimbattery` and `require('lualine').setup`

**Comment by Norok-The-Diablo** [comment]
sounds good

**Comment by Norok-The-Diablo** [comment]
works just fine!

**Comment by Norok-The-Diablo** [comment]
thanks so much

**Comment by justinhj** [comment]
Thanks to you both. I just sat down and updated my Windows desktop since it was still on Neovim 0.7 lol
By the time I had replicated the issue and create a branch to fix it I saw @Agent-E11 had fixed already!
Thanks again
