### ISSUE TITLE
bug(parsers): `vim.fn.has()` isn't being properly checked

### ISSUE THREAD

**Issue by Agent-E11** [justinhj/battery.nvim#53]
In `lua/battery/parsers/powershell.lua`, the `M.check` function is checked as if it was a boolean, but it actually returns `0` or `1`. This means that if it isn't on Windows, but powershell is executable (like on WSL), powershell will be selected as the method (which causes an error)

**Comment by justinhj** [comment]
Good spot ty will fix

**Comment by Agent-E11** [comment]
@justinhj um... sorry 😅 #54
